import re
import commands
from os.path import expanduser
HOME = expanduser("~")

# head -n 600 fuseki_extime.txt>y_time.txt 
# head -n 800 fuseki_extime.txt|tail -n 200 > yval_time.txt
# tail -n 200 fuseki_extime.txt > ytest_time.txt 


TOTAL_QUERY = 10000

#this is the log file generated by fuseki
FUSEKILOG_FILE = "fuseki-10000.nogit"

#dont change below

FUSEKI_EXTIME_FILE = "fuseki_extime_log.nogit"
FUSEKI_FINAL_EXTIME_FILE = "fuseki_extime.txt"

DIRECTORY = str(TOTAL_QUERY)

FUSEKILOG_FILE = DIRECTORY+"/"+FUSEKILOG_FILE
FUSEKI_EXTIME_FILE = DIRECTORY+"/"+FUSEKI_EXTIME_FILE
FUSEKI_FINAL_EXTIME_FILE = DIRECTORY+"/"+FUSEKI_FINAL_EXTIME_FILE

def process_fuseki_log():
    #log_file = open(FUSEKILOG_FILE,'r')
    grep_cmd = 'grep -o ":: \[[[:digit:]]\+\] 200 OK \(.\+\)" '+FUSEKILOG_FILE+'> '+FUSEKI_EXTIME_FILE
    (status,abs_query_str) = commands.getstatusoutput(grep_cmd)
    #print abs_query_str
    if status != 0:
        print "Grep error", status
        print grep_cmd
        return
    f = open(FUSEKI_EXTIME_FILE,'r')
    ff = open(FUSEKI_FINAL_EXTIME_FILE,'w')
    for line in f:
        et = get_fuseki_execution_time(line)
        ff.write(str(et)+'\n')


def get_fuseki_execution_time(log_str):
    expr = r'.+\((.+)\s(.+)\)'
    match = re.findall(expr, log_str)
    #print match
    (et,unit) = match[0]
    et = float(et)
    if unit == "s":
        et = et * 100.0
    print et
    return et



def main():
    process_fuseki_log()

if __name__ == "__main__":
    main()

